Neos:
  Media:
    assetSources:
      wikipedia:
        assetSource: 'DL\AssetSource\Wikimedia\AssetSource\WikimediaAssetSource'
        assetSourceOptions:
#          domain: de.wikipedia.org
          domain: commons.wikimedia.org
          searchStrategy: DL\AssetSource\Wikimedia\Api\SearchStrategies\DirectImageSearchStrategy
