Neos:
  Media:
    assetSources:
      wikipedia:
        assetSource: 'DL\AssetSource\MediaWiki\AssetSource\MediaWikiAssetSource'
        assetSourceOptions:
          domain: en.wikipedia.org
          searchStrategy: DL\AssetSource\MediaWiki\Api\SearchStrategies\ArticleSearchStrategy
          useQueryResultCache: true
          excludedIdentifierPatterns:
            - '*Wikiquote-logo.svg'
            - '*Wikinews-logo.svg'
            - '*Commons-logo.svg'
            - '*Disambig-dark.svg'
            - '*Pictogram voting info.svg'
            - '*Loudspeaker.svg'
