Neos:
  Media:
    assetSources:
      wikipedia:
        assetSource: 'DL\AssetSource\MediaWiki\AssetSource\MediaWikiAssetSource'
        assetSourceOptions:
#          domain: de.wikipedia.org
          domain: commons.wikimedia.org
#          searchStrategy: DL\AssetSource\MediaWiki\Api\SearchStrategies\ArticleSearchStrategy
          searchStrategy: DL\AssetSource\MediaWiki\Api\SearchStrategies\DirectImageSearchStrategy
          excludedIdentifierPatterns:
            - '*Wikiquote-logo.svg'
            - '*Wikinews-logo.svg'
            - '*Commons-logo.svg'
            - '*Disambig-dark.svg'
            - '*Pictogram voting info.svg'
            - '*Loudspeaker.svg'
